### ISSUE TITLE
Module to get someone's avatar 

### ISSUE THREAD

**Issue by ghost** [GooseMod-Modules/Requests#1]
Just copy the link **or** open the avatar image in discord like it was a normal image and then with right click there would be options to copy the link, copy the image, etc.. (**idk if it's possible just an idea**).

**Comment by CanadaHonk** [comment]
[Was just made](https://github.com/GooseMod-Modules/CopyAvatarURL), and just added to the Module Store.

**Comment by ghost** [comment]
@CanadaHonk it doesn't work with gifs it needs a dedicated option for it.
