### ISSUE TITLE
[Request] Could I have my theme "SlideToUnlock" put on the store?

### ISSUE THREAD

**Issue by SlippingGitty** [GooseMod-Modules/Requests#10]
https://github.com/SlippingGitty/SlideToUnlock
Thank you for your time. c: I apologize if this is improper formatting of a request, or the wrong repo to place one.

**Comment by CanadaHonk** [comment]
Sure! I'm doing something right now but I'll do it when I'm free. Could I get your Discord user ID for the author?

**Comment by CanadaHonk** [comment]
Adding it now.

**Comment by CanadaHonk** [comment]
Added to the Module Store!
