### ISSUE TITLE
Request to add my theme Nebula to the store

### ISSUE THREAD

**Issue by ghost** [GooseMod-Modules/Requests#12]
I'm trying to add universal support to my theme.
Link: https://github.com/euphorianic/Nebula

![DiscordCanary_Sj0efbHB3G](https://user-images.githubusercontent.com/73035923/108922906-da0aff80-7605-11eb-8ce8-aa17baedf55e.png)

**Comment by CanadaHonk** [comment]
Thanks for the request, we'll finish working on PC theme porting and then add this to the Module Store.

**Comment by CanadaHonk** [comment]
Was completed last week.
