### ISSUE TITLE
Spotify integration without Premium

### ISSUE THREAD

**Issue by Dziurwa14** [GooseMod-Modules/Requests#18]
Allows you to listen along without premium
powercord version: https://github.com/slow/spotify-crack

enhanceddiscord version: https://raw.githubusercontent.com/juby210-PL/EnhancedDiscord-plugins/master/spotify_crack.js

**Comment by CanadaHonk** [comment]
Seems meh on the whether to include side but likely with a different name.

**Comment by Dziurwa14** [comment]
Ah okay

**Comment by Dziurwa14** [comment]
Can use MS2Builder now.
