### ISSUE TITLE
[Request] May I have my forked theme "WinClassic" on the store?

### ISSUE THREAD

**Issue by SlippingGitty** [GooseMod-Modules/Requests#21]
https://github.com/SlippingGitty/WinClassic

Thank you for your time. > <

**Comment by CanadaHonk** [comment]
Could you please send the user IDs of the authors here? Thanks.

**Comment by SlippingGitty** [comment]
Of course! 

@ D Mack#4481 
@ icanttellyou#5786

edit: See Dziurwa14 for Dmack and icantellyou's IDs, oops. 

There are some extra additions to the theme I did to fix, improve, or change entirely. I'd like to be credited as well, if that's okay. 

Mine: 359175647257690113

**Comment by Dziurwa14** [comment]
D Mack ID: 324260038736871426
icanttellyou ID : 224565309133029379

**Comment by CanadaHonk** [comment]
Thanks, I'll get on it in a bit.

**Comment by CanadaHonk** [comment]
Apologies for the wait. Just to clarify, it will be added via an autoport so your "WinClassicTheme.js" file is not needed, thanks.

**Comment by CanadaHonk** [comment]
It's now in the store, thank you for your submission!
