### ISSUE TITLE
Requesting to put my theme Cozy202K on the modules store

### ISSUE THREAD

**Issue by SlippingGitty** [GooseMod-Modules/Requests#24]
https://github.com/SlippingGitty/Cozy202K

Screenshot:
 ![screenshot](https://i.imgur.com/MITe9oU.png)

My ID: 359175647257690113

Thank you for your time. <3

**Comment by CanadaHonk** [comment]
Doing now, could you contact me on Discord?

**Comment by CanadaHonk** [comment]
Added
