### ISSUE TITLE
Module that clones the emote you selected to the server you want

### ISSUE THREAD

**Issue by ghost** [GooseMod-Modules/Requests#3]
Right click the emote, and then show a option to clone and an option to select the server you want to clone the emote to.

**Comment by CanadaHonk** [comment]
Adding an emote to a server automatically would likely require API calls so likely not possible. Keeping open but adding label.

**Comment by Cynosphere** [comment]
Fulfilled: https://github.com/Cynosphere/hjonk/tree/master/createEmoji
